# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import grid.models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=grid.models.get_image_path),
        ),
    ]
