# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0002_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('T', 'Top'), ('B', 'Bottom'), ('A', 'Accessory')], max_length=1, null=True),
        ),
    ]
