# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 23:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0003_article_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='type',
            new_name='article_type',
        ),
    ]
