# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0005_auto_20160629_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('T', 'Top'), ('B', 'Bottom'), ('D', 'Dress'), ('A', 'Details')], max_length=1, null=True),
        ),
    ]
