# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0007_auto_20160629_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('T', 'Top'), ('B', 'Bottom'), ('D', 'Dress'), ('A', 'Details'), ('O', 'Outer'), ('S', 'Shoes')], max_length=1, null=True),
        ),
    ]
