# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import grid.models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0010_auto_20160630_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to=grid.models.get_image_path),
        ),
    ]
