# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0011_auto_20160630_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='weather_type',
            field=models.CharField(choices=[('A', 'All'), ('C', 'Cool'), ('W', 'Warm')], max_length=1, null=True),
        ),
    ]
