# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0012_article_weather_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='weather_type',
            field=models.CharField(choices=[('C', 'Cool'), ('W', 'Warm'), ('B', 'Both')], max_length=1, null=True),
        ),
    ]
