# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0014_auto_20160630_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='name',
            field=models.CharField(default='W', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='weather_type',
            field=models.CharField(choices=[('W', 'Winter'), ('P', 'Spring'), ('S', 'Summer'), ('A', 'Autumn')], max_length=1, null=True),
        ),
    ]
