# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0015_auto_20160701_0719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='weather_type',
            new_name='season_type',
        ),
    ]
