# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0017_outfit'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_external',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
