# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import grid.models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0019_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(null=True, upload_to=grid.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(choices=[('F', 'Free'), ('P', 'Paid')], max_length=1, null=True),
        ),
    ]
