# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0021_auto_20160703_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_external',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(choices=[('F', 'Free'), ('P', 'Paid')], default='F', max_length=1),
        ),
    ]
