# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0022_auto_20160704_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='articles',
            field=models.ManyToManyField(to='grid.Article'),
        ),
    ]
