# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0028_article_image_slurp'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_slurp',
            field=models.URLField(blank=True, null=True),
        ),
    ]
