# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0029_auto_20160710_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='public',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False),
        ),
    ]
